# Generated by Django 2.2.9 on 2020-01-17 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EndSpot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=150, unique=True)),
                ('note', models.TextField()),
            ],
            options={
                'permissions': (('add_flowdata_under_this_end_spot', 'Add FlowData records under This EndSpot'),),
            },
        ),
        migrations.CreateModel(
            name='FlowData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DecimalField(db_index=True, decimal_places=6, max_digits=20)),
                ('value', models.FloatField()),
                ('create_time', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('end_spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_store.EndSpot')),
            ],
        ),
    ]
